export  const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export  const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export  const LOGIN_FAIL = "LOGIN_FAIL"
export  const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export  const REGISTER_FAIL = "REGISTER_FAIL"
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const CUSTOMER_SUCCESS ="CUSTOMER_SUCCESS"

export const SHIPMENT_SUCCESS = "SHIPMENT_SUCCESS"

export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS"